In [2]:
import numpy as np

## 1

In [14]:
print(np.zeros(10))
print(np.ones(10))
print(np.ones(10) * 5)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


------------------------------------------------------------------------

## 2

In [4]:
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

------------------------------------------------------------------------

## 3

In [5]:
np.zeros(shape=(5,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

------------------------------------------------------------------------

## 4

In [6]:
arr = np.random.rand(10,10)
print(arr)
print(np.min(arr))
print(np.max(arr))

[[0.68655793 0.90438337 0.29567974 0.54491484 0.7672255  0.79875542
  0.69695185 0.92437779 0.1000992  0.18096479]
 [0.85249223 0.80274558 0.07900771 0.92964438 0.30747898 0.27086355
  0.73862009 0.71148541 0.36487496 0.90521234]
 [0.02065888 0.6607674  0.65252948 0.86334229 0.97582818 0.33264045
  0.62201391 0.98935913 0.50040355 0.06188625]
 [0.71523139 0.34805649 0.3925814  0.17024944 0.37590531 0.82718365
  0.50809962 0.30503996 0.31562427 0.29762796]
 [0.29894979 0.62377909 0.91721369 0.32326324 0.71084772 0.90015261
  0.11419078 0.32006318 0.15216981 0.08811385]
 [0.63199063 0.67562456 0.32609975 0.63206986 0.03971713 0.28569608
  0.68886432 0.21476039 0.27989067 0.38545202]
 [0.53069199 0.61611572 0.5035974  0.84798388 0.31550742 0.36189323
  0.49846156 0.81211684 0.20702958 0.43883763]
 [0.54316093 0.48625487 0.40101168 0.25406808 0.30665245 0.48110476
  0.19283963 0.27879341 0.77248222 0.55291482]
 [0.50694151 0.71718333 0.27129779 0.97335142 0.55121311 0.60838387
  0.19021875

------------------------------------------------------------------------

## 5

In [13]:
np.random.randint(2, 10, size=(3,3))

array([[3, 9, 9],
       [2, 2, 8],
       [3, 3, 7]])

------------------------------------------------------------------------

## 6

In [8]:
arr = np.arange(stop=20)
arr[arr > 15]


array([16, 17, 18, 19])

------------------------------------------------------------------------

## 7

In [9]:
arr1 = np.array([[0, 1, 3],
                 [5, 7, 9]])
arr2 = np.array([[0, 2, 4],
                 [6, 8, 10]])

print(np.hstack((arr1,arr2)))
print()
print(np.vstack((arr1,arr2)))

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]

[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]


------------------------------------------------------------------------

## 8

In [10]:
ones = np.ones(shape=(10,), dtype=int)
ones[5] = 11
print(ones)


[ 1  1  1  1  1 11  1  1  1  1]


------------------------------------------------------------------------

## 9

In [11]:
arr = np.array([5,10,15])
arr_after_append = np.append(arr , 100)
print(arr_after_append)

[  5  10  15 100]


------------------------------------------------------------------------

## 10

## Flip: Can used in 2d-array to flip rows, columns or both

In [12]:
arr = np.array([100, 200, 300, 500])
arr_flip1 = arr[::-1]
arr_flip2 = np.flip(arr)

print(arr_flip1)
print()
print(arr_flip2)

[500 300 200 100]

[500 300 200 100]
